CREATE TABLE IF NOT EXISTS CO_TRIGGERS (
    TRIGGER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    APP_ID BIGINT NOT NULL,
    NOTICE_PDF BLOB,
    TRIGGER_STATUS VARCHAR(50),
    FAILURE_REASON VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
